---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8qu-controller-rolebinding
  namespace: {{ $.Release.Namespace }}
  labels:
    {{ template "k8qu.common-labels" . }}
subjects:
  - kind: ServiceAccount
    name: k8qu-controller
    namespace: {{ $.Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: k8qu-controller-role
  apiGroup: rbac.authorization.k8s.io