apiVersion: k8qu.io/v1alpha1
kind: Job
metadata:
  name: fill-the-queue
spec:
  queue: "deadline"

  templates:
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        generateName: configmap-b
      data:
        a: b

