apiVersion: k8qu.io/v1alpha1
kind: Job
metadata:
  name: simple-job
spec:
  queue: "abc"
  completed: false
  failed: false
  timeout: "20s"

  templates:
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: configmap-a
      data:
        a: b
