apiVersion: k8qu.io/v1alpha1
kind: QueueJob
metadata:
  name: simple-job-2
spec:
  queue: "abc"
  completed: false
  failed: false
  executionTimeout: "20s"

  templates:
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: configmap-b
      data:
        a: b
