apiVersion: k8qu.io/v1alpha1
kind: QueueJob
metadata:
  name: max-time-in-queue
spec:
  queue: "max-time-in-queue"
  maxTimeInQueue: "10s"

  templates:
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        generateName: configmap-b
      data:
        a: b

