apiVersion: k8qu.io/v1alpha1
kind: QueueJob
metadata:
  name: multi-resource-job
spec:
  queue: "multiq"
  completed: false
  failed: false
  executionTimeout: "20s"

  templates:
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: mr-1
      data:
        a: b
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: mr-2
      data:
        a: b
