apiVersion: k8qu.io/v1alpha1
kind: QueueJob
metadata:
  name: templates-on-failure
spec:
  queue: "tos"

  onFailureTemplates:
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: i-am-failed
      data:
        a: b

  templates:
    - apiVersion: batch/v1
      kind: Job
      metadata:
        generateName: tos-
      spec:
        ttlSecondsAfterFinished: 10
        template:
          spec:
            serviceAccountName: auto-complete-me
            containers:
              - name: kubectl
                image: bitnami/kubectl
                command:
                  - "kubectl"
                  - "patch"
                  - "queuejobs.k8qu.io"
                  - "[[JOBNAME]]"
                  - "--type"
                  - "merge"
                  - "--patch"
                  - '{"spec":{"failed":true}}'
            restartPolicy: Never
