apiVersion: k8qu.io/v1alpha1
kind: QueueJob
metadata:
  name: templates-on-timeout
spec:
  queue: "templates-on-timeout"
  executionTimeout: "5s"

  templates:
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        generateName: configmap-b
      data:
        a: b

  onExecutionTimeoutTemplates:
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        generateName: was-timed-out
      data:
        a: b

