apiVersion: k8qu.io/v1alpha1
kind: QueueJob
metadata:
  name: timeout-on-queue-settings
spec:
  queue: "parallel-two"

  templates:
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        generateName: configmap-b
      data:
        a: b

