apiVersion: k8qu.io/v1alpha1
kind: Job
metadata:
  name: timeout
spec:
  queue: "timeout"
  timeout: "5s"

  templates:
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: configmap-a
      data:
        a: b
