apiVersion: k8qu.io/v1alpha1
kind: QueueJob
metadata:
  name: auto-complete-me
spec:
  queue: "auto-complete"
  executionTimeout: "20s"

  templates:
  - apiVersion: batch/v1
    kind: Job
    metadata:
      generateName: acm-
    spec:
      ttlSecondsAfterFinished: 10
      template:
        spec:
          serviceAccountName: auto-complete-me
          containers:
            - name: kubectl
              image: bitnami/kubectl
              command:
              - "kubectl"
              - "patch"
              - "jobs.k8qu.io"
              - "auto-complete-me"
              - "--type"
              - "merge"
              - "--patch"
              - '{"spec":{"completed":true}}'
          restartPolicy: Never
