apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: jobs.k8qu.io
spec:
  group: k8qu.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      additionalPrinterColumns:
        - name: Queue
          type: string
          description: Name of the queue
          jsonPath: .spec.queue
        - name: StartedAt
          type: date
          jsonPath: .status.startedAt
        - name: CompletedAt
          type: date
          jsonPath: .status.completedAt
        - name: Outcome
          type: string
          jsonPath: .status.outcome
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: ["queue", "templates"]
              properties:
                queue:
                  type: string
                completed:
                  type: boolean
                failed:
                  type: boolean
                timeout:
                  type: string
                deadlineTimeout:
                  type: string
                ttlAfterSuccesfullCompletion:
                  type: string
                ttlAfterFailedCompletion:
                  type: string
                templates:
                  type: array
                  items:
                    type: object
                    x-kubernetes-embedded-resource: true
                    x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              properties:
                completedAt:
                  type: string
                startedAt:
                  type: string
                isSuccessfull:
                  type: boolean
                outcome:
                  type: string
  names:
    kind: Job
    plural: jobs
  scope: Namespaced
