apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: markqueuejobcompletes.k8qu.io
spec:
  group: k8qu.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      additionalPrinterColumns:
        - name: Queue
          type: string
          description: Name of the queue
          jsonPath: .spec.queue
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              # TODO:
              # validate when completed is set = only true
              # validate when failed is set = only true
              properties:
                queue:
                  type: string
                completed:
                  type: boolean
                completedParts:
                  type: array
                  items:
                    type: string
                failed:
                  type: boolean
  names:
    kind: MarkQueueJobComplete
    plural: markqueuejobcompletes
  scope: Namespaced
