apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: queuesettings.k8qu.io
spec:
  group: k8qu.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      additionalPrinterColumns:
        - name: Parallelism
          type: integer
          jsonPath: .spec.parallelism
        - name: executionTimeout
          type: string
          jsonPath: .spec.executionTimeout
        - name: maxTimeInQueue
          type: string
          jsonPath: .spec.maxTimeInQueue
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parallelism:
                  type: integer
                ttlAfterSuccessfulCompletion:
                  type: string
                ttlAfterFailedCompletion:
                  type: string
                executionTimeout:
                  type: string
                maxTimeInQueue:
                  type: string
  names:
    kind: QueueSettings
    plural: queuesettings
  scope: Namespaced
