apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: queuesettings.k8qu.io
spec:
  group: k8qu.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      additionalPrinterColumns:
        - name: Parallelism
          type: integer
          jsonPath: .spec.parallelism
        - name: ttlAfterSuccesfullCompletion
          type: integer
          jsonPath: .spec.ttlAfterSuccesfullCompletion
        - name: ttlAfterFailedCompletion
          type: integer
          jsonPath: .spec.ttlAfterFailedCompletion
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parallelism:
                  type: integer
                ttlAfterSuccesfullCompletion:
                  type: string
                ttlAfterFailedCompletion:
                  type: string
                timeout:
                  type: string
                deadlineTimeout:
                  type: string
  names:
    kind: QueueSettings
    plural: queuesettings
  scope: Namespaced
